# SwiftLintの対象外とする
excluded:
BuildTools/

# 無効とするルール
disabled_rules:
- file_length
- function_body_length
- type_body_length


# デフォで無効とされたルールを有効とする
opt_in_rules:
- conditional_returns_on_newline
- closure_end_indentation
- closure_spacing


# ルールをカスタム
line_length: 450

type_name:
  min_length: 2
  max_length: 50

vertical_whitespace:
 max_empty_lines: 2